// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `{ code, message }`: the error shape every Tauri command returns (`CLAUDE.md`: "`AppError`
 * serializes to `{ code, message }` with `code` from a fixed list the UI can translate").
 *
 * `code` is stable, machine-readable, and the thing the UI should switch/translate on (Italian
 * strings live in `apps/mobile/src/i18n/it.ts`, never hard-coded in Rust). `message` is an
 * English, non-sensitive detail string (never a path, SQL, or key material) — a reasonable
 * fallback/log line, not meant to be shown to the user verbatim.
 */
export type AppError = { code: string, message: string, };
