// Hand-written to mirror `scrigno_core::meta::DocMeta` (crates/scrigno-core/src/meta.rs).
//
// NOT generated by `ts-rs`: `scrigno-core` has no `ts-rs` wiring yet (out of scope for M4, see
// `apps/mobile/src-tauri/src/types.rs`'s module docs). Field names and order match the Rust
// struct's `serde` output exactly (no `#[serde(rename...)]` present on the Rust side, so no
// casing differences to account for).
//
// Keep in sync with `crates/scrigno-core/src/meta.rs` by hand if that struct ever changes.

/** Decrypted document metadata, as returned by the `doc_get_meta` Tauri command. */
export type DocMeta = {
  /** Metadata schema version. */
  v: number;
  /** User-chosen document title. */
  title: string;
  /** User-chosen tags. */
  tags: Array<string>;
  /** Free-text note. */
  note: string;
  /** MIME type of the underlying blob. */
  mime: string;
  /**
   * Plaintext size in bytes. Rust `u64`, transported as a plain JSON number (unlike the
   * `bigint`-typed fields in the `ts-rs`-generated bindings, this hand-written type keeps it as
   * `number` since that is what actually arrives over IPC's JSON transport).
   */
  size: number;
  /** Hex-encoded BLAKE3 hash of the plaintext blob. */
  content_hash: string;
  /** Original file name as chosen by the user. */
  original_name: string;
  /** RFC 3339 creation timestamp. */
  created_at: string;
  /** Base64-encoded JPEG thumbnail (≤ 24 KiB), or `null`. */
  thumb: string | null;
};
