// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A client-owned projection of one document: the decrypted [`scrigno_core::meta::DocMeta`]
 * fields (minus `thumb` — per `docs/ARCHITECTURE.md §6`'s `docs_list` note, the thumbnail is
 * fetched separately on demand) plus local sync bookkeeping the UI/CLI needs to render a list
 * and know what will happen on the next `sync()`.
 *
 * Rebuilt entirely in memory from `enc_meta` on unlock ([`crate::vault::Vault::unlock`]);
 * never persisted in decrypted form (`docs/CRYPTO.md §5.3`).
 */
export type DocSummary = { 
/**
 * Document id (`UUIDv7`), as a string.
 */
id: string, 
/**
 * User-chosen title.
 */
title: string, 
/**
 * User-chosen tags.
 */
tags: Array<string>, 
/**
 * Free-text note.
 */
note: string, 
/**
 * MIME type of the underlying blob.
 */
mime: string, 
/**
 * Plaintext size in bytes.
 */
size: bigint, 
/**
 * Hex-encoded BLAKE3 hash of the plaintext.
 */
content_hash: string, 
/**
 * Original file name as chosen by the user.
 */
original_name: string, 
/**
 * RFC 3339 creation timestamp.
 */
created_at: string, 
/**
 * The local row's version. Equal to `base_version` when the row is not `dirty`.
 */
version: bigint, 
/**
 * `true` if this row has a local change not yet pushed to the server.
 */
dirty: boolean, 
/**
 * `true` if the blob must always be kept in the local cache (never LRU-evicted).
 */
keep_offline: boolean, 
/**
 * Size in bytes of the encrypted blob on the server (ciphertext size, not `size`).
 */
blob_size: bigint, 
/**
 * `true` if the blob's ciphertext is currently present in the local cache.
 */
cached: boolean, };
