// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `settings_get`/`settings_set`'s payload (`docs/ARCHITECTURE.md §6`).
 *
 * `server_url` is read-only after the vault is created/joined (`docs/ARCHITECTURE.md §7`):
 * `commands::settings_set` silently ignores an attempt to change it rather than erroring, so a
 * caller that round-trips `settings_get`'s output through `settings_set` unchanged never fails.
 */
export type Settings = { 
/**
 * Inactivity timeout in minutes before the vault auto-locks (`docs/CRYPTO.md §5.2`), 1–30,
 * default 5.
 */
auto_lock_minutes: number, 
/**
 * Local blob cache size limit in MiB (`docs/ARCHITECTURE.md §4`), default 512. Only
 * changeable while unlocked (backed by `UnlockedVault::set_cache_limit_mb`).
 */
cache_limit_mb: bigint, 
/**
 * The server URL entered at setup. Read-only after `vault_create`/`vault_join`.
 */
server_url: string, 
/**
 * Whether quick unlock (`docs/CRYPTO.md §5.2`, `crate::quick_unlock`) is currently enrolled
 * on this device. Always `false` on desktop (no quick-unlock concept there — see
 * `commands::vault_unlock_quick`'s desktop stub); reflects real enrollment
 * (`quick_unlock::is_enabled`) on Android. Read-only: there is no `settings_set` field for
 * this — enrollment/un-enrollment go through `vault_enable_quick_unlock`/
 * `vault_forget_quick_unlock` instead.
 */
quick_unlock_enabled: boolean, };
