// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One non-fatal condition observed during a [`crate::vault::UnlockedVault::sync`] call. Never
 * pre-localized to Italian in this crate (CLAUDE.md: UI strings live in
 * `apps/mobile/src/i18n/it.ts`, never hard-coded in Rust); the UI maps `kind`/fields to a
 * phrase at render time.
 */
export type SyncWarning = { "kind": "ServerRollback", 
/**
 * The document id the out-of-order record was for.
 */
doc_id: string, 
/**
 * The local cursor at the time the record was observed.
 */
cursor: bigint, 
/**
 * The record's own `server_seq`, which was `<= cursor`.
 */
server_seq: bigint, };
