// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncWarning } from "./SyncWarning";

/**
 * Outcome of one [`crate::vault::UnlockedVault::sync`] call.
 */
export type SyncReport = { 
/**
 * Number of remote change records applied locally (including conflict copies created).
 */
pulled: number, 
/**
 * Number of local dirty rows successfully pushed to the server.
 */
pushed: number, 
/**
 * Number of conflict copies created during this call.
 */
conflicts: number, 
/**
 * Non-fatal warnings observed during this call.
 */
warnings: Array<SyncWarning>, };
