//! Shared `OsRng` helper.
//!
//! This is the only place `OsRng` is touched directly; every nonce, salt, and key in this
//! crate is generated by calling [`fill_random`], so an audit for "is randomness sourced from
//! `OsRng`, and only `OsRng`" (CRYPTO.md §9) has exactly one call site to check.

use rand::TryRngCore;
use rand::rngs::OsRng;

use crate::error::Error;

/// Fills `buf` with cryptographically secure random bytes from `OsRng`.
///
/// # Errors
/// Returns [`Error::Internal`] if the OS random number generator reports a failure. This is
/// extremely rare in practice (a working `getrandom`/`/dev/urandom` is assumed to exist) but
/// is propagated rather than panicking, per this crate's no-panic-on-any-input policy.
pub(crate) fn fill_random(buf: &mut [u8]) -> Result<(), Error> {
    OsRng.try_fill_bytes(buf).map_err(|_| Error::Internal)
}
